name: C++ Build and Test Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install GCC
      run: sudo apt update && sudo apt install -y g++
      
    - name: Compile and Run Tests
      run: |
        g++ -o testApp Logic_Gate.cpp circuit.cpp testOperator.cpp main.cpp
        ./testApp
        
